/// <reference types="@sveltejs/kit" />
import { build, files, version } from '$service-worker';

const CACHE = `cheki-cache-v${version}`;

// Core application routes to cache for offline SPA navigation
const ROUTES = ['/', '/admin', '/capture', '/processing', '/result'];

// All static assets generated by Vite and located in /static
const ASSETS = [
	...ROUTES,
	...build,
	...files
];

self.addEventListener('install', (event) => {
	self.skipWaiting();
	async function addFilesToCache() {
		const cache = await caches.open(CACHE);
		for (const asset of ASSETS) {
			try {
				await cache.add(asset);
			} catch (e) {
				console.warn('[SW] Precache item skipped:', asset, e);
			}
		}
	}
	event.waitUntil(addFilesToCache());
});

self.addEventListener('activate', (event) => {
	event.waitUntil(
		(async () => {
			await self.clients.claim();
			const keys = await caches.keys();
			for (const key of keys) {
				if (key !== CACHE) {
					console.log('[SW] Purging outdated cache:', key);
					await caches.delete(key);
				}
			}
		})()
	);
});

self.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Never intercept Cloudinary uploads, Cloudflare functions API, or cross-origin assets
	if (url.origin !== self.location.origin || url.pathname.startsWith('/api/')) {
		return;
	}

	async function respond() {
		const cache = await caches.open(CACHE);

		// 1. If requesting an exact build chunk or static asset, serve from cache first
		if (build.includes(url.pathname) || files.includes(url.pathname)) {
			const cachedResponse = await cache.match(event.request);
			if (cachedResponse) return cachedResponse;
		}

		// 2. Try network first
		try {
			const response = await fetch(event.request);
			if (response.status === 200) {
				cache.put(event.request, response.clone());
			}
			return response;
		} catch (err) {
			// 3. Network failed (offline) -> Look up in cache
			const cachedResponse = await cache.match(event.request);
			if (cachedResponse) return cachedResponse;

			// If it's a page navigation request (e.g. clicking /capture while offline),
			// fall back to the cached root / index.html so SvelteKit SPA router takes over!
			if (event.request.mode === 'navigate') {
				const fallback = (await cache.match('/')) || (await cache.match('/index.html'));
				if (fallback) return fallback;
			}

			throw err;
		}
	}

	event.respondWith(respond());
});
